Minor Fix For Plugin Defaults
AgnostiqHQ/covalent-awsbatch-plugin pull request #87
Opened 2023-10-26 09:54 UTC by mpvgithub

Fixed:
- Changed the `prefix` attribute of `ExecutorPluginDefaults` to take a default value

2023-10-30 17:25 UTC, kessler-frost requested changes

2023-10-30 17:25 UTC, kessler-frost commented on CHANGELOG.md
> +
Shouldn't this be under `Changed` instead? Or was it causing an error which got fixed once a default value was passed?

2023-10-30 17:25 UTC, kessler-frost commented on covalent_awsbatch_plugin/awsbatch.py
> +    prefix: Optional[str] = ""
Do we need to make this `Optional` or is assigning a default value to it sufficient? Also, I think the default value should be an appropriate value, maybe `default-awsbatch-prefix` or something instead of an empty string.

2023-10-31 04:16 UTC, mpvgithub commented on CHANGELOG.md
> +
@kessler-frost,

This was causing an error when using with `deploy` when other arguments such as **aws_region**, **profile** are passed to the `up` command.

2023-10-31 04:16 UTC, mpvgithub commented on covalent_awsbatch_plugin/awsbatch.py
> +    prefix: Optional[str] = ""
@kessler-frost,

We will make the necessary changes.

2023-10-31 05:55 UTC, kessler-frost commented on CHANGELOG.md
> +
Thanks! In that case let's rephrase it so that the problem it solved is also indicated.

2023-11-06 08:17 UTC, kessler-frost approved these changes

2023-11-06 08:22 UTC, merged