Require no variables to covalent deploy awsbatch
AgnostiqHQ/covalent-awsbatch-plugin pull request #88
Opened 2023-11-30 03:44 UTC by araghukas

### Changed

- Edit terraform scripts to require no user input in most cases (maybe `region`).

---

- [ ] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

2023-12-05 15:37 UTC, kessler-frost requested changes

2023-12-05 15:37 UTC, kessler-frost commented on covalent_awsbatch_plugin/assets/infra/iam.tf
> -  name               = "${var.prefix}-task-execution-role"
Why are we changing all these prefixes to suffixes and still calling them prefixes?

2023-12-05 15:37 UTC, kessler-frost commented on covalent_awsbatch_plugin/assets/infra/iam.tf
> -  name = "${var.prefix}-instance-profile"
Is there any benefit of switching from `var.` to `local.`?

2023-12-05 16:50 UTC, araghukas commented on covalent_awsbatch_plugin/assets/infra/iam.tf
> -  name               = "${var.prefix}-task-execution-role"
Just seemed more conventional this way, i.e. "real-words-r4nd0m5tr" or "real-words-my_custom_str" when the var `prefix` is specified, as opposed to "r4nd0m5tr-real-words". The var name "prefix" exists across deployments, however, so I didn't change it to "suffix" here (maybe I should have...).

It is weird as is though, like you've correctly pointed out.

I guess the options here are:
1. change this (and gcp) to use prefix as an actual prefix
2. change `prefix` to `suffix` everywhere (here and gcp and eventually azure)

Probably no.1 is the easier option, tho I'm fine with doing no.2 as well since PRs are already out here. But up to you @kessler-frost -- there's no reason why it *needs* be called "prefix", right?

2023-12-05 16:54 UTC, araghukas commented on covalent_awsbatch_plugin/assets/infra/iam.tf
> -  name = "${var.prefix}-instance-profile"
Local lets us overload it dynamically with a generated default value. Variable declarations have to be "static" in terraform as far as I know. Not even function calls are allowed in variables.

Here, if the variable `var.prefix` is not specified, it'll have the variable's default (`''`), which we can detect and overload with a random string e.g. `locals { prefix = var.prefix != '' ? var.prefix : random_string.default_prefix.result }`

2023-12-05 19:00 UTC, kessler-frost commented on covalent_awsbatch_plugin/assets/infra/iam.tf
> -  name               = "${var.prefix}-task-execution-role"
I would kinda argue against the "real-words-r4nd0m5tr" pattern in favor of "r4nd0m5tr-real-words", my reasoning for that for this particular case is that:
1. It'll make things easier to find on the management console, e.g.:
        - "donatello-task-execution-super-long-role-name"
        - "leo-task-execution-super-long-role-name"
        - "michaelangelo-task-execution-super-long-role-name"
        - "raphael-task-execution-super-long-role-name"

        ^ is easier to read and determine to who/which type of task the resource belongs to, vs.

        - "task-execution-super-long-role-name-donatello"
        - "task-execution-super-long-role-name-leo"
        - "task-execution-super-long-role-name-michaelangelo"
        - "task-execution-super-long-role-name-raphael"
        
        especially once you have lots of different types of resources in your AWS dashboard (and if the "name" column hides the full name)
2. It requires minimal changes since most of the other cloud executors I believe also follow this same pattern, though I'm not a 100% sure for the reason behind it

And yeah, I would also prefer the first option :sweat_smile: .

2023-12-05 19:03 UTC, kessler-frost commented on covalent_awsbatch_plugin/assets/infra/iam.tf
> -  name               = "${var.prefix}-task-execution-role"
Actually, I think an even better one would be `covalent-r4nd0m5tr-real-words`. If the prefix isn't specified by the user. If that's doable?

2023-12-05 19:04 UTC, kessler-frost commented on covalent_awsbatch_plugin/assets/infra/iam.tf
> -  name = "${var.prefix}-instance-profile"
Thanks! Makes sense.

2023-12-06 01:40 UTC, araghukas commented on covalent_awsbatch_plugin/assets/infra/iam.tf
> -  name               = "${var.prefix}-task-execution-role"
yea totally, just have to rearrange some strings... will get back you soon

2023-12-06 17:13 UTC, kessler-frost approved these changes

2023-12-06 17:13 UTC, merged